import {describe,expect,it,vi} from 'vitest';
import {createAppServer} from './http.ts';
import {CarrierService} from './carrier-service.ts';
import {WeatherService} from './weather-service.ts';
import type {AddressInfo} from 'node:net';
async function start(service?:WeatherService){const server=createAppServer({dist:'.',carrierService:new CarrierService('.not-used-weather-test'),weatherService:service,allowedOrigins:['https://localhost']});await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));return {url:`http://127.0.0.1:${(server.address() as AddressInfo).port}/api/v1/weather`,close:()=>new Promise<void>(r=>{server.closeAllConnections();server.close(()=>r());})};}
describe('weather HTTP boundary',()=>{
  it('reports disabled status without making an upstream request or implying a forecast',async()=>{const app=await start();try{const r=await fetch(app.url+'/status');expect(await r.json()).toEqual({data:{available:false}});expect(r.headers.get('cache-control')).toBe('no-store');expect((await fetch(app.url+'/places?q=Berlin')).status).toBe(503);}finally{await app.close();}});
  it('refuses unsupported actions, bodies, duplicate params, external URLs and invalid IDs before any provider call',async()=>{const provider=vi.fn(),app=await start(new WeatherService('noncommercial',undefined,provider));try{for(const path of ['/places?q=Berlin&url=https://other.test','/places?q=Berlin&q=Paris','/forecast?placeId=0','/forecast?placeId=http://localhost','/status?q=Berlin'])expect((await fetch(app.url+path)).status).toBe(400);expect((await fetch(app.url+'/unknown')).status).toBe(404);expect((await fetch(app.url+'/places?q=Berlin',{method:'POST',body:'private'})).status).toBe(405);expect(provider).not.toHaveBeenCalled();}finally{await app.close();}});
  it('permits explicit native origins but rejects other browser origins before provider access',async()=>{const provider=vi.fn().mockImplementation(()=>Promise.resolve(new Response('{}',{headers:{'Content-Type':'application/json'}}))),app=await start(new WeatherService('noncommercial',undefined,provider));try{expect((await fetch(app.url+'/places?q=Berlin',{headers:{Origin:'https://other.test'}})).status).toBe(403);expect(provider).not.toHaveBeenCalled();const r=await fetch(app.url+'/places?q=Berlin',{headers:{Origin:'https://localhost'}});expect(r.headers.get('Access-Control-Allow-Origin')).toBe('https://localhost');expect(r.headers.get('Access-Control-Allow-Credentials')).toBeNull();expect(await r.json()).toEqual({data:[]});}finally{await app.close();}});
  it('does not return internal errors, credentials or partial forecasts on source failure',async()=>{const app=await start(new WeatherService('noncommercial',undefined,vi.fn().mockRejectedValue(Error('private-key/internal-path'))));try{const r=await fetch(app.url+'/forecast?placeId=2950159');expect(r.status).toBe(503);expect(await r.text()).not.toContain('private-key');}finally{await app.close();}});
});
