import {describe,expect,it,vi} from 'vitest';
import {WeatherService,parseWeatherForecast,parseWeatherPlace} from './weather-service.ts';
import {WEATHER_SOURCE} from '../src/weather.ts';
const at='2026-10-01T12:00:00Z',now=()=>Date.parse(at);
const place={id:2950159,name:'Berlin',country:'Germany',country_code:'DE',latitude:52.52,longitude:13.41,timezone:'Europe/Berlin'};
const weather=()=>({latitude:52.5,longitude:13.4,timezone:'Europe/Berlin',daily_units:{time:'iso8601',temperature_2m_min:'°C',temperature_2m_max:'°C',precipitation_probability_max:'%'},daily:{time:['2026-10-01','2026-10-02'],temperature_2m_min:[8,null],temperature_2m_max:[26,20],precipitation_probability_max:[50,null]}});
const response=(data:unknown)=>new Response(JSON.stringify(data),{headers:{'Content-Type':'application/json'}});
describe('fixed-source weather provider',()=>{
  it('fails closed by default and validates access/key configuration',async()=>{const fetcher=vi.fn();const service=new WeatherService('off',undefined,fetcher,now);expect(service.available).toBe(false);await expect(service.search('Berlin')).rejects.toThrow();expect(fetcher).not.toHaveBeenCalled();expect(()=>new WeatherService('commercial')).toThrow();expect(()=>new WeatherService('noncommercial','secret')).toThrow();expect(()=>new WeatherService('unexpected' as never)).toThrow();});
  it('maps real provider fields and preserves missing observations, grid and body hash',()=>{const raw=JSON.stringify(weather()),f=parseWeatherForecast(weather(),parseWeatherPlace(place),at,raw);expect(f).toMatchObject({provider:'open_meteo',sourceUrl:WEATHER_SOURCE,gridLatitude:52.5,place:{id:2950159}});expect(f.sourceHash).toHaveLength(64);expect(f.days[1].minC).toBeNull();});
  it('refuses changed units, lengths, timezones, invalid dates and nonnumeric source values',()=>{for(const mutate of [(v:ReturnType<typeof weather>)=>v.daily_units.temperature_2m_min='°F',(v:ReturnType<typeof weather>)=>v.daily.temperature_2m_min.pop(),(v:ReturnType<typeof weather>)=>v.timezone='UTC',(v:ReturnType<typeof weather>)=>v.daily.time[0]='2026-02-30',(v:ReturnType<typeof weather>)=>v.daily.temperature_2m_max[0]=NaN]){const value=weather();mutate(value);expect(()=>parseWeatherForecast(value,parseWeatherPlace(place),at,'fixture')).toThrow();}});
  it('searches bounded exact upstreams and never requests trip dates or belongings',async()=>{const fetcher=vi.fn().mockResolvedValue(response({results:[place]})),service=new WeatherService('noncommercial',undefined,fetcher,now);expect(await service.search('Berlin, Germany')).toHaveLength(1);const [target,options]=fetcher.mock.calls[0];expect(target.origin).toBe('https://geocoding-api.open-meteo.com');expect(target.pathname).toBe('/v1/search');expect([...target.searchParams.keys()].sort()).toEqual(['count','format','language','name']);expect(options).toMatchObject({credentials:'omit',redirect:'error'});expect(target.searchParams.get('count')).toBe('5');});
  it('resolves the place ID again then requests metric daily data without trip context',async()=>{const fetcher=vi.fn().mockResolvedValueOnce(response(place)).mockResolvedValueOnce(response(weather())),service=new WeatherService('noncommercial',undefined,fetcher,now);expect((await service.forecast(place.id)).days).toHaveLength(2);const url=fetcher.mock.calls[1][0];expect(url.origin).toBe('https://api.open-meteo.com');expect(url.searchParams.get('forecast_days')).toBe('16');expect(url.searchParams.get('timezone')).toBe('Europe/Berlin');expect(url.searchParams.has('start_date')).toBe(false);});
  it('keeps the commercial key server-side and uses only customer hosts',async()=>{const fetcher=vi.fn().mockResolvedValueOnce(response(place)).mockResolvedValueOnce(response(weather())),service=new WeatherService('commercial','private-key',fetcher,now),result=await service.forecast(place.id);expect(fetcher.mock.calls.map(c=>c[0].hostname)).toEqual(['customer-geocoding-api.open-meteo.com','customer-api.open-meteo.com']);expect(fetcher.mock.calls.every(c=>c[0].searchParams.get('apikey')==='private-key')).toBe(true);expect(JSON.stringify(result)).not.toContain('private-key');});
  it('rejects changed place identities and outdated first dates',async()=>{let fetcher=vi.fn().mockResolvedValue(response({...place,id:1}));await expect(new WeatherService('noncommercial',undefined,fetcher,now).forecast(place.id)).rejects.toThrow();expect(fetcher).toHaveBeenCalledTimes(1);const old=weather();old.daily.time=['2026-09-30','2026-10-01'];fetcher=vi.fn().mockResolvedValueOnce(response(place)).mockResolvedValueOnce(response(old));await expect(new WeatherService('noncommercial',undefined,fetcher,now).forecast(place.id)).rejects.toThrow(/date/);});
  it('bounds streamed responses and rejects redirects, errors and non-JSON content',async()=>{for(const reply of [new Response('x'.repeat(150001),{headers:{'content-type':'application/json'}}),new Response('{}',{status:500}),new Response('{}',{headers:{'content-type':'text/html'}})]){await expect(new WeatherService('noncommercial',undefined,vi.fn().mockResolvedValue(reply),now).search('Berlin')).rejects.toThrow();}});
  it('refuses duplicate place identities, malformed results and explicit provider errors',async()=>{for(const reply of [{results:[place,place]},{results:'bad'},{error:true},{results:[{...place,latitude:999}]}])await expect(new WeatherService('noncommercial',undefined,vi.fn().mockResolvedValue(response(reply)),now).search('Berlin')).rejects.toThrow();});
  it('returns a genuine empty search without inventing a place and bounds calls before fetching',async()=>{const fetcher=vi.fn().mockImplementation(()=>Promise.resolve(response({}))),service=new WeatherService('noncommercial',undefined,fetcher,now);for(let i=0;i<20;i++)expect(await service.search('Berlin')).toEqual([]);await expect(service.search('Berlin')).rejects.toThrow(/limit/);expect(fetcher).toHaveBeenCalledTimes(20);await expect(service.forecast(-1)).rejects.toThrow();await expect(service.search('x')).rejects.toThrow();expect(fetcher).toHaveBeenCalledTimes(20);});
});
