import type { ContainerCompartment, Evidence, UnitSystem } from '../types';
import { ITEM_CATEGORIES, MAX_COMPARTMENTS } from '../compartments';
import { measurementFromInput, measurementInput } from '../measurement-input';

export function CompartmentFields({ compartments, onChange, unit }: { compartments: ContainerCompartment[]; onChange: (value: ContainerCompartment[]) => void; unit: UnitSystem }) {
  const factor = unit === 'metric' ? 1 : 25.4, massFactor = unit === 'metric' ? 1 : 28.3495;
  const label = unit === 'metric' ? 'mm' : 'inches';
  const recorded = (source: Evidence['source']): Evidence => ({ source, confidence: source === 'estimated' ? .5 : 1, collectedAt: new Date().toISOString(), note: 'Traveller-recorded compartment; not detected or measured by the scan.' });
  function update(id: string, change: Partial<ContainerCompartment>, review = true) {
    onChange(compartments.map(c => c.id === id ? { ...c, ...change, ...(review ? { supportEvidence: recorded('estimated') } : {}) } : c));
  }
  return <section className="compartment-fields" aria-label="Usable bag compartments">
    <h3>Usable compartments</h3><p>Record separate rectangular areas with independent top access. Once added, only these areas are usable: record the main area too. Positions start at the bag's inside corner. Stacked or side-opening pockets need a different access model.</p>
    {compartments.map((c, index) => <fieldset className="compartment-card" key={c.id}><legend>Compartment {index + 1}</legend>
      <label className="field"><span>Name</span><input aria-label={`Compartment ${index + 1} name`} maxLength={80} value={c.name} onChange={e => update(c.id, { name: e.target.value }, false)}/></label>
      <div className="space-coordinate-fields">{([['x', 'From left'], ['y', 'From front'], ['z', 'Above floor'], ['length', 'Length'], ['width', 'Width'], ['height', 'Height']] as const).map(([key, title]) => <label className="field" key={key}><span>{title} · {label}</span><input aria-label={`Compartment ${index + 1} ${title.toLowerCase()}`} type="number" inputMode="decimal" min={['x', 'y', 'z'].includes(key) ? 0 : .0001} step="any" value={Number.isFinite(c[key]) ? measurementInput(c[key], factor) : ''} onChange={e => { const value = e.target.value.trim() === '' ? NaN : measurementFromInput(e.target.value, factor, c[key]); if (!Object.is(value, c[key])) update(c.id, { [key]: value, evidence: recorded(c.evidence.source) }); }}/></label>)}</div>
      <div className="dimension-fields">{(['length', 'width'] as const).map(key => <label className="field" key={key}><span>Top opening {key} · {label}</span><input aria-label={`Compartment ${index + 1} opening ${key}`} type="number" inputMode="decimal" min="0.0001" step="any" value={Number.isFinite(c.opening[key]) ? measurementInput(c.opening[key], factor) : ''} onChange={e => { const value = e.target.value.trim() === '' ? NaN : measurementFromInput(e.target.value, factor, c.opening[key]); if (!Object.is(value, c.opening[key])) update(c.id, { opening: { ...c.opening, [key]: value }, evidence: recorded(c.evidence.source) }); }}/></label>)}</div>
      <label className="field"><span>Dimension source</span><select aria-label={`Compartment ${index + 1} dimension source`} value={c.evidence.source} onChange={e => update(c.id, { evidence: recorded(e.target.value as Evidence['source']) }, false)}>{(['estimated', 'measured', 'user_confirmed'] as const).map(source => <option key={source} value={source}>{source === 'estimated' ? 'Estimated' : source === 'measured' ? 'Measured by you' : 'Confirmed by you'}</option>)}{!['estimated', 'measured', 'user_confirmed'].includes(c.evidence.source) && <option value={c.evidence.source}>{c.evidence.source}</option>}</select></label>
      <label className="field"><span>Contents weight limit · {unit === 'metric' ? 'grams' : 'ounces'} <em>optional</em></span><input aria-label={`Compartment ${index + 1} contents weight limit`} type="number" inputMode="decimal" min="0.0001" step="any" value={measurementInput(c.massLimitGrams, massFactor)} onChange={e => { const value = e.target.value.trim() === '' ? undefined : measurementFromInput(e.target.value, massFactor, c.massLimitGrams); if (!Object.is(value, c.massLimitGrams)) update(c.id, { massLimitGrams: value, massLimitEvidence: value === undefined ? undefined : recorded(c.massLimitEvidence?.source ?? 'user_confirmed') }); }}/></label>
      {c.massLimitGrams !== undefined && <label className="field"><span>Contents limit source</span><select aria-label={`Compartment ${index + 1} contents limit source`} value={c.massLimitEvidence?.source ?? 'user_confirmed'} onChange={e => update(c.id, { massLimitEvidence: recorded(e.target.value as Evidence['source']) })}>{(['estimated', 'known', 'measured', 'user_confirmed', 'provider'] as const).map(source => <option key={source} value={source}>{source.replace('_', ' ')}</option>)}</select></label>}
      <fieldset className="compartment-categories"><legend>Eligible item categories</legend><label className="check-row"><input type="checkbox" checked={c.allowedCategories === undefined} onChange={e => update(c.id, { allowedCategories: e.target.checked ? undefined : [...ITEM_CATEGORIES] })}/><span>Allow every category</span></label>{c.allowedCategories !== undefined && ITEM_CATEGORIES.map(category => <label className="check-row" key={category}><input type="checkbox" checked={c.allowedCategories!.includes(category)} onChange={e => update(c.id, { allowedCategories: e.target.checked ? [...c.allowedCategories!, category] : c.allowedCategories!.filter(value => value !== category) })}/><span>{category}</span></label>)}</fieldset>
      <label className="check-row compartment-review"><input aria-label={`Compartment ${index + 1} access and support reviewed`} type="checkbox" checked={c.supportEvidence.source === 'user_confirmed'} onChange={e => update(c.id, { supportEvidence: recorded(e.target.checked ? 'user_confirmed' : 'estimated') }, false)}/><span>I checked independent top access and closed bases that support these contents in both packing and travel positions. I will check actual fit and strength.</span></label><small>Changing the area, opening, limit or categories requires another review. Packed positions remain saved and may pause this bag.</small>
      <button className="text-button" type="button" onClick={() => onChange(compartments.filter(value => value.id !== c.id))}>Remove compartment {index + 1}</button>
    </fieldset>)}
    <button className="button button-secondary" type="button" disabled={compartments.length >= MAX_COMPARTMENTS} onClick={() => onChange([...compartments, { id: crypto.randomUUID(), name: '', x: 0, y: 0, z: 0, length: NaN, width: NaN, height: NaN, opening: { length: NaN, width: NaN }, evidence: recorded('estimated'), supportEvidence: recorded('estimated') }])}>Add usable compartment</button><small>{compartments.length} of {MAX_COMPARTMENTS} recorded. Removing every compartment restores whole-bag planning; old packed compartment positions need review.</small>
  </section>;
}
