import { useEffect, useRef, useState } from 'react';
import { accountRequest, AccountRequestError, type PackingAccountProfile } from '../account-client';
import { isSharedPackSnapshot, sharedPackingRecords, type HouseholdDetail, type HouseholdSummary, type SharedPackSnapshot, type SharedPackSummary } from '../shared-packs';
import type { AppData } from '../types';
import {createSharedPackBaseline,type SharedPackBaseline} from '../shared-pack-baseline';
import type {SharedCopyWitness} from '../shared-packs';
import {SharedPackCombination} from './SharedPackCombination';
import {useDeviceWorkspace} from './DeviceWorkspace';
import { downloadAccountFile as download } from '../native-account';

export function HouseholdPanel({data,profile,csrf,onOpen,onPublished,onExpired}:{data:AppData;profile:PackingAccountProfile;csrf:string;onOpen:(snapshot:SharedPackSnapshot,baseline?:SharedPackBaseline,witness?:SharedCopyWitness)=>void;onPublished:(tripId:string,snapshot:SharedPackSnapshot,baseline:SharedPackBaseline)=>void;onExpired:()=>void}) {
  const [houses,setHouses]=useState<HouseholdSummary[]>([]),[selected,setSelected]=useState(''),[detail,setDetail]=useState<HouseholdDetail>();
  const [busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[name,setName]=useState(''),[username,setUsername]=useState('');
  const [joinCode,setJoinCode]=useState(''),[joinConsent,setJoinConsent]=useState(false),[invitation,setInvitation]=useState<{code:string;expiresAt:string;username:string}>();
  const [tripId,setTripId]=useState(data.activeTripId),[shareConsent,setShareConsent]=useState(false),[password,setPassword]=useState(''),[nextOwner,setNextOwner]=useState('');
  const trip=data.trips.find(trip=>trip.id===tripId),owner=detail?.ownerId===profile.id;
  const device=useDeviceWorkspace(),alive=useRef(true),latest=useRef(data);latest.current=data;
  useEffect(()=>{alive.current=true;return()=>{alive.current=false;};},[]);
  async function openSnapshot(snapshot:SharedPackSnapshot){
    const start=latest.current;if(!isSharedPackSnapshot(snapshot))throw Error('This shared version is unsupported. Local records are unchanged.');
    const baseline=await createSharedPackBaseline(snapshot.records,snapshot.revision);
    device.checkActive();if(!alive.current||latest.current!==start)throw Error('The workspace or local records changed. Review the shared version again.');
    onOpen(snapshot,baseline);
  }

  useEffect(()=>{let active=true;accountRequest<HouseholdSummary[]>('/households').then(result=>{if(active)setHouses(result);}).catch(error=>{if(active)setNotice(error instanceof Error?error.message:'Households are unavailable.');});return()=>{active=false;};},[profile.id]);
  useEffect(()=>{setShareConsent(false);},[data,selected,tripId]);
  useEffect(()=>{setTripId(data.activeTripId);},[data.activeTripId]);
  async function run(action:()=>Promise<void>){setBusy(true);setNotice('');try{await action();}catch(error){if(error instanceof AccountRequestError){if(error.code==='sign_in_required')onExpired();if(error.code==='shared_pack_conflict')setShareConsent(false);if(error.code==='household_not_found'){setDetail(undefined);setSelected('');setHouses(await accountRequest<HouseholdSummary[]>('/households').catch(()=>[]));}}setNotice(error instanceof Error?error.message:'The household request failed.');}finally{setBusy(false);}}
  async function reload(id=selected){setHouses(await accountRequest<HouseholdSummary[]>('/households'));if(id)setDetail(await accountRequest<HouseholdDetail>(`/households/${id}`));setShareConsent(false);}
  async function choose(id:string){setSelected(id);setDetail(undefined);setInvitation(undefined);setPassword('');setNextOwner('');if(id)setDetail(await accountRequest<HouseholdDetail>(`/households/${id}`));}
  return <section className="household-panel" aria-label="Household sharing"><h3>Household sharing</h3>
    <p>Members can view and edit packs explicitly shared with their household. Your private backup and unused personal library stay separate. Nothing is shared automatically.</p>
    <div className="account-form"><label className="field"><span>New household name</span><input maxLength={80} value={name} onChange={e=>setName(e.target.value)}/></label><button className="button button-secondary" disabled={busy||!name.trim()} onClick={()=>void run(async()=>{const result=await accountRequest<HouseholdSummary>('/households','POST',{name},csrf);setName('');await reload('');await choose(result.id);setNotice('Household created. No packing records have been shared.');})}>Create household</button></div>
    <details><summary>Join an invited household</summary><label className="field"><span>Private household invitation code</span><input type="password" autoComplete="off" value={joinCode} onChange={e=>setJoinCode(e.target.value)}/></label><label className="account-check"><input type="checkbox" checked={joinConsent} disabled={busy} onChange={e=>setJoinConsent(e.target.checked)}/><span>I agree to join the household addressed to this account. Members will see my display name and username and can access its shared packs. The owner controls membership; saved copies cannot be recalled.</span></label><button className="button button-secondary" disabled={busy||!joinCode||!joinConsent} onClick={()=>void run(async()=>{const result=await accountRequest<HouseholdSummary>('/households/memberships','POST',{code:joinCode,consent:true},csrf);setJoinCode('');setJoinConsent(false);await reload('');await choose(result.id);setNotice('Joined the household. Local packing records are unchanged.');})}>Accept household invitation</button></details>
    <label className="field"><span>Household to review</span><select aria-label="Household to review" value={selected} disabled={busy} onChange={e=>void run(()=>choose(e.target.value))}><option value="">Choose a household</option>{houses.map(house=><option key={house.id} value={house.id}>{house.name}</option>)}</select></label>
    <button className="button button-secondary" disabled={busy} onClick={()=>void run(async()=>{await reload();setNotice('Current household membership and pack versions loaded. Local copies are unchanged.');})}>Reload households</button>
    {detail&&<><h4>{detail.name}</h4><p>{owner?'You own this household.':'You are a household member.'} Every current member can open and publish its shared packs.</p>
      <ul className="household-members">{detail.members.map(member=><li key={member.id}>{member.name} · {member.username}{member.id===detail.ownerId?' · owner':''}{owner&&member.id!==profile.id&&<button className="button button-secondary" disabled={busy} onClick={()=>void run(async()=>{if(!window.confirm(`Remove ${member.name} from this household? Their saved copies will remain.`))return;await accountRequest(`/households/${detail.id}/members/${member.id}`,'DELETE',undefined,csrf);await reload();setNotice('Membership removed. Previously saved copies cannot be recalled.');})}>Remove member</button>}</li>)}</ul>
      {owner&&<details><summary>Invite an existing packing account</summary><label className="field"><span>Invited account username</span><input autoCapitalize="none" spellCheck={false} maxLength={40} value={username} onChange={e=>setUsername(e.target.value)}/></label><p>The invitation is addressed to this username, expires after 48 hours and works once. Give the code privately to that person. They must sign in and accept; creating the code sends no message.</p><button className="button button-secondary" disabled={busy||!username.trim()} onClick={()=>void run(async()=>{const result=await accountRequest<{code:string;expiresAt:string}>(`/households/${detail.id}/invitations`,'POST',{username},csrf);setInvitation({...result,username:username.trim()});await reload();setNotice('Private invitation created. No message was sent.');})}>Create private invitation</button>
        {invitation&&<aside className="account-recovery household-invitation" aria-label="Private household invitation"><p>For {invitation.username} · expires {new Date(invitation.expiresAt).toLocaleString()}</p><code>{invitation.code}</code><div className="account-actions"><button className="button button-secondary" disabled={busy} onClick={()=>void run(async()=>{const saved=await download('packing-household-invitation.txt',`Household invitation\nAccount: ${invitation.username}\nCode: ${invitation.code}\nExpires: ${invitation.expiresAt}\nKeep private. Sign in to the addressed packing account to accept.\n`);setNotice(saved?'Invitation code exported. Keep it private.':'Invitation export cancelled.');})}>Download invitation code</button><button className="button button-secondary" onClick={()=>setInvitation(undefined)}>I saved the invitation</button></div></aside>}
        <ul>{detail.invitations.map(invite=><li key={invite.id}>Pending for {invite.username} · expires {new Date(invite.expiresAt).toLocaleString()} <button className="button button-secondary" disabled={busy} onClick={()=>void run(async()=>{await accountRequest(`/households/${detail.id}/invitations/${invite.id}`,'DELETE',undefined,csrf);setInvitation(undefined);await reload();setNotice('Pending invitation revoked.');})}>Revoke invitation</button></li>)}</ul>
      </details>}
      <section className="household-packs" aria-label="Shared household packs"><h4>Shared packs</h4>{!detail.packs.length&&<p>No packs shared yet.</p>}
        <ul>{detail.packs.map(pack=><li key={pack.id}><strong>{pack.name}</strong> · version {pack.revision} · {new Date(pack.updatedAt).toLocaleString()}<div className="account-actions"><button className="button button-secondary" disabled={busy} onClick={()=>void run(async()=>{const snapshot=await accountRequest<SharedPackSnapshot>(`/households/${detail.id}/packs/${pack.id}`);if(!isSharedPackSnapshot(snapshot))throw Error('This shared version is unsupported. Local records are unchanged.');await openSnapshot(snapshot);setNotice('Shared version opened as a separate local copy. Earlier packs and source files are unchanged.');})}>Open separate local copy</button><button className="button button-secondary" disabled={busy} onClick={()=>void run(async()=>{const saved=await download('packing-household-pack.json',await accountRequest<SharedPackSnapshot>(`/households/${detail.id}/packs/${pack.id}`));setNotice(saved?'Shared pack downloaded. Keep its private records safe.':'Shared pack export cancelled.');})}>Download shared pack</button>{owner&&<button className="button button-danger" disabled={busy} onClick={()=>void run(async()=>{if(!window.confirm(`Delete the reviewed shared version of ${pack.name} from this household? Local and downloaded copies remain.`))return;await accountRequest(`/households/${detail.id}/packs/${pack.id}`,'DELETE',{revision:pack.revision,confirm:true},csrf);await reload();setNotice('Current shared pack deleted. Saved local copies remain.');})}>Delete shared pack</button>}</div></li>)}</ul>
        <label className="field"><span>Local pack to share or publish</span><select aria-label="Local pack to share or publish" value={tripId} disabled={busy} onChange={e=>setTripId(e.target.value)}><option value="">Choose a local pack</option>{data.trips.map(trip=><option key={trip.id} value={trip.id}>{trip.name}{trip.sharedPack?` · local version ${trip.sharedPack.revision}`:''}</option>)}</select></label>
        {trip&&<p>Includes {trip.entries.length} item entries, {trip.containerIds.length} bags, traveller names, travel details, measurements, adopted geometry and recorded packing progress from “{trip.name}”. Photos, original capture files and unused library items are excluded.{trip.sharedPack?.householdId===detail.id?` This copy was opened at version ${trip.sharedPack.revision}.`:''}</p>}
        <label className="account-check"><input type="checkbox" checked={shareConsent} disabled={busy||!trip} onChange={e=>setShareConsent(e.target.checked)}/><span>I agree to share these selected-pack records with every member of {detail.name}. Members can edit and download them, and saved copies cannot be recalled.</span></label>
        <button className="button button-primary" disabled={busy||!trip||!shareConsent} onClick={()=>void run(async()=>{const records=sharedPackingRecords(data,trip!.id),link=trip!.sharedPack?.householdId===detail.id?trip!.sharedPack:undefined;const started=latest.current,baseline=await createSharedPackBaseline(records,link?link.revision+1:1);device.checkActive();if(!alive.current||latest.current!==started)throw Error('Local records changed before publication. Review the pack and consent again.');const result=await accountRequest<SharedPackSummary&{householdId:string}>(`/households/${detail.id}/packs${link?`/${link.packId}`:''}`,link?'PUT':'POST',{records,consent:true,...(link?{revision:link.revision}:{})},csrf);const snapshot={...result,records};if(!isSharedPackSnapshot(snapshot)||snapshot.revision!==baseline.revision)throw Error('The shared request was saved but its local copy could not be confirmed. Reload the household before retrying.');try{device.checkActive();if(!alive.current)throw Error();}catch{throw Error('Publication was confirmed by the server, but this workspace changed or locked. Reload its shared version after opening the original workspace.');}if(link)onPublished(trip!.id,snapshot,baseline);else onOpen(snapshot,baseline);setShareConsent(false);await reload();setNotice(link?'Shared changes published. Other local copies remain unchanged.':'Pack shared and opened as a separate local copy. Your original private pack is unchanged.');})}>{trip?.sharedPack?.householdId===detail.id?'Publish this shared copy':'Share selected pack'}</button>
        <p>Local edits work offline and stay on this device until published. A newer server version blocks a stale publish. Open it separately, or review a combined copy against the saved baseline. Publication remains deliberate; earlier local copies are preserved.</p>
      </section>
      {trip?.sharedPack?.householdId===detail.id&&<SharedPackCombination key={`${profile.id}:${trip.id}`} data={data} tripId={trip.id} onOpen={onOpen} onExpired={onExpired}/>}
      <details><summary>Household ownership and removal</summary>{owner?<><label className="field"><span>Household owner password</span><input type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)}/></label><label className="field"><span>New household owner</span><select aria-label="New household owner" value={nextOwner} onChange={e=>setNextOwner(e.target.value)}><option value="">Choose another member</option>{detail.members.filter(member=>member.id!==profile.id).map(member=><option key={member.id} value={member.id}>{member.name} · {member.username}</option>)}</select></label><div className="account-actions"><button className="button button-secondary" disabled={busy||!nextOwner||!password} onClick={()=>void run(async()=>{if(!window.confirm('Transfer household ownership to this member? They will control invitations, membership and deletion.'))return;await accountRequest(`/households/${detail.id}/ownership`,'POST',{userId:nextOwner,password,confirm:true},csrf);setPassword('');await reload();setNotice('Household ownership transferred. You remain a member.');})}>Transfer household ownership</button><button className="button button-danger" disabled={busy||!password} onClick={()=>void run(async()=>{if(!window.confirm(`Delete ${detail.name}, its invitations, memberships and all shared packs? Download any shared packs you need first. Local and downloaded copies remain.`))return;await accountRequest(`/households/${detail.id}`,'DELETE',{password,confirm:true},csrf);setPassword('');await choose('');await reload('');setNotice('Household and current shared records deleted. Local copies remain.');})}>Delete household</button></div></>:<button className="button button-secondary" disabled={busy} onClick={()=>void run(async()=>{if(!window.confirm('Leave this household? You will lose server access; your saved local copies will remain.'))return;await accountRequest(`/households/${detail.id}/members/${profile.id}`,'DELETE',undefined,csrf);await choose('');await reload('');setNotice('Left the household. Local copies remain.');})}>Leave household</button>}<p>To delete an account that owns a household with other members, first transfer ownership or explicitly delete that household. Removing access cannot recall files already saved on another device.</p></details>
    </>}
    {busy&&<p role="status">Working on household request…</p>}{notice&&<p role="status" className="account-notice">{notice}</p>}
  </section>;
}
