import type { PackingShape, UprightDirection } from '../types';
import { packingShapeError,shapeDimensions,shapeVolume } from '../packing-geometry';
import { UprightReview } from './UprightReview';
import { uprightRecordError } from '../upright';
export function PackingShapeCard({shape,onRemove,keepUpright,onUpright}:{shape:PackingShape;onRemove:()=>void;keepUpright:boolean;onUpright:(record:UprightDirection|undefined)=>void}) {
  if(packingShapeError({dimensions:shape.fittedDimensionsMm,packingShape:shape}))return <section aria-label="Adopted packing shape"><p role="alert">The saved shape needs correction before planning.</p>{uprightRecordError(shape)&&<button className="button button-secondary" type="button" onClick={()=>onUpright(undefined)}>Clear invalid upright review</button>}<button className="button button-secondary" type="button" onClick={onRemove}>Use rectangular bounds</button></section>;
  const {grid,resolutionMm,occupiedCells}=shape.solid,projected=[...new Set(occupiedCells.map(cell=>cell%(grid.x*grid.y)))];
  const bounds=shapeDimensions(shape),ratio=shape.fittedDimensionsMm.length/shape.sourceEnvelopeMm.length;
  return <section className="surface-reconstruction" aria-label="Adopted packing shape"><h3>Estimated packing shape</h3><p>The plan uses these occupied cells, including open recesses. Other items use rectangular bounds. This does not verify physical completeness or fit.</p><svg className="solid-surface-top" role="img" aria-label="Saved packing shape top projection" viewBox={`-5 -5 ${grid.x*resolutionMm+10} ${grid.y*resolutionMm+10}`}>{projected.map(cell=><rect key={cell} x={cell%grid.x*resolutionMm} y={Math.floor(cell/grid.x)*resolutionMm} width={resolutionMm} height={resolutionMm} fill="#409573"/>)}</svg><p>Planning envelope: {bounds.length.toFixed(2)} × {bounds.width.toFixed(2)} × {bounds.height.toFixed(2)} mm. Cell rounding is retained at { (resolutionMm*ratio).toFixed(2)} mm spacing. Occupied-cell volume: {(shapeVolume(shape)/1e6).toFixed(3)} litres.</p><UprightReview key={shape.solid.id+':'+shape.solid.sourceHash} shape={shape} keepUpright={keepUpright} onChange={onUpright}/><details><summary>Source information</summary><small>Adopted {new Date(shape.adoptedAt).toLocaleString()}. Source fingerprint: {shape.solid.sourceHash}. Backups retain this derivative, not the original scan.</small></details><button className="button button-secondary" type="button" onClick={onRemove}>Use rectangular bounds</button></section>;
}
