import {packingStepRelation} from './packing-sequence';
import {geometryContactArea,hasPackingAndTravelSupport,hasVerticalEntry,fitsGeometrySpace} from './packing-geometry';
import {describe,it,expect} from 'vitest';
import {createInitialData} from './seed';
import {buildPlan} from './optimizer';
import {containerSpaceError,usableContainerVolume,fitsUsableContainer} from './container-space';
import {compartmentKey,fitsCompartment} from './compartments';
import {isPackingBackup} from './backup';
import {sharedPackingRecords,openSharedPack} from './shared-packs';
import {samePlacementGeometry} from './packing-progress';
import type {ContainerCompartment,OptimizationMode} from './types';
const evidence={source:'measured' as const,confidence:1,collectedAt:'2026-10-01T00:00:00Z'};
function region(id='left',x=0):ContainerCompartment{return {id,name:id,x,y:0,z:0,length:180,width:200,height:200,opening:{length:180,width:200},evidence,supportEvidence:{...evidence,source:'user_confirmed'}};}
function fixture(){const app=structuredClone(createInitialData()),bag=app.containers[0],item=app.libraryItems[0],trip=app.trips[0];bag.inside={length:400,width:200,height:200};bag.opening={length:400,width:200};bag.compartments=[region(),region('right',220)];bag.massLimitGrams=undefined;bag.tareGrams=0;item.dimensions={length:80,width:80,height:80};item.keepUpright=true;item.fragile=false;item.massGrams=100;item.massRangeGrams=undefined;trip.entries=[{id:'entry',itemId:item.id,travellerId:trip.travellers[0].id,quantity:1,priority:'required',required:true,accessPriority:3}];trip.lockedPlacements=[];trip.completedInstanceIds=[];return {app,bag,item,trip,plan:(mode?:OptimizationMode)=>buildPlan(trip,[item],[bag],mode)};}
describe('recorded compartments',()=>{
  it('uses only recorded regions and their own openings in every mode',()=>{for(const mode of ['balanced','maximum_capacity','easy_access','fragile_protection'] as OptimizationMode[]){const f=fixture();f.bag.compartments![0].opening={length:50,width:50};const p=f.plan(mode);expect(p.placements).toHaveLength(1);expect(p.placements[0].compartmentId).toBe('right');expect(p.placements[0].x).toBeGreaterThanOrEqual(220);expect(fitsCompartment(p.placements[0],f.bag)).toBe(true);expect(p.summaries[0].volumeCapacityMm3).toBe(14_400_000);}});
  it('also enforces the parent opening and overhead intrusions along the whole insertion path',()=>{const f=fixture();f.bag.opening={length:70,width:70};expect(f.plan().placements).toHaveLength(0);f.bag.opening={length:400,width:200};f.bag.compartments![0].height=100;f.trip.entries[0].containerId=f.bag.id;f.trip.entries[0].compartmentId='left';f.bag.unavailableSpaces=[{id:'overhead',name:'Overhead intrusion',x:0,y:0,z:190,length:180,width:200,height:10,evidence}];expect(f.plan().placements).toHaveLength(0);f.bag.unavailableSpaces=undefined;const saved=f.plan().placements[0];f.trip.lockedPlacements=[saved];f.trip.completedInstanceIds=[saved.instanceId];f.bag.opening={length:70,width:70};expect(f.plan().placements).toHaveLength(0);expect(f.trip.lockedPlacements).toEqual([saved]);});
  it('supports an explicitly reviewed raised floor without using an intrusion as a floor',()=>{const f=fixture(),c=f.bag.compartments![1];c.z=100;c.height=100;f.trip.entries[0].containerId=f.bag.id;f.trip.entries[0].compartmentId=c.id;const p=f.plan();expect(p.placements).toHaveLength(1);expect(p.placements[0].z).toBe(100);expect(p.placements[0].compartmentKey).toBe(compartmentKey(c));expect(packingStepRelation(p.placements[0],p.placements,[f.item],f.bag)).toContain('floor of “right”');expect(fitsUsableContainer(p.placements[0],f.bag)).toBe(true);expect(fitsUsableContainer({...p.placements[0],compartmentId:undefined},f.bag)).toBe(false);});
  it('keeps assignment and category eligibility hard instead of falling back to another region',()=>{const f=fixture();f.bag.compartments![1].allowedCategories=['documents'];f.item.category='clothing';f.trip.entries[0].containerId=f.bag.id;f.trip.entries[0].compartmentId='right';expect(f.plan().placements).toHaveLength(0);expect(f.plan().requiredExcludedCount).toBe(1);f.trip.entries[0].compartmentId=undefined;expect(f.plan().placements[0].compartmentId).toBe('left');});
  it('refuses unknown contents weights and applies separate contents and gross bag limits',()=>{const f=fixture();f.bag.compartments![0].massLimitGrams=150;f.bag.compartments![0].massLimitEvidence=evidence;f.trip.entries[0].containerId=f.bag.id;f.trip.entries[0].compartmentId='left';f.trip.entries[0].quantity=2;expect(f.plan().placements).toHaveLength(1);f.item.massGrams=undefined;expect(f.plan().placements).toHaveLength(0);f.item.massGrams=300;f.trip.entries[0].compartmentId=undefined;f.bag.compartments![0].massLimitGrams=undefined;f.bag.tareGrams=500;f.bag.massLimitGrams=1000;expect(f.plan().placements).toHaveLength(1);});
  it('subtracts intrusion overlap and lid space only within the compartment union',()=>{const f=fixture();f.bag.lidClearanceMm=20;f.bag.lidClearanceEvidence=evidence;f.bag.unavailableSpaces=[{id:'frame',name:'frame',x:0,y:0,z:0,length:90,width:200,height:200,evidence}];expect(usableContainerVolume(f.bag)).toBe(9_720_000);f.trip.entries[0].containerId=f.bag.id;f.trip.entries[0].compartmentId='left';expect(f.plan().placements[0].x).toBeGreaterThanOrEqual(90);});
  it('rejects duplicate/outside/stacked footprints, missing review and malformed restrictions',()=>{const variants=[(c:ContainerCompartment)=>c.x=300,(c:ContainerCompartment)=>c.id='left',(c:ContainerCompartment)=>c.x=50,(c:ContainerCompartment)=>c.opening.length=181,(c:ContainerCompartment)=>c.supportEvidence.source='estimated',(c:ContainerCompartment)=>c.allowedCategories=[]];for(const change of variants){const f=fixture();change(f.bag.compartments![1]);expect(containerSpaceError(f.bag)).toBeTruthy();expect(f.plan().placements).toHaveLength(0);}const f=fixture();f.trip.entries[0].compartmentId='right';expect(f.plan().placements).toHaveLength(0);});
  it('preserves raw packed locks while pausing changed geometry or assignments',()=>{const f=fixture();f.trip.entries[0].containerId=f.bag.id;f.trip.entries[0].compartmentId='right';const saved=f.plan().placements[0];f.trip.lockedPlacements=[saved];f.trip.completedInstanceIds=[saved.instanceId];f.bag.compartments![1].name='Renamed';expect(f.plan().placements[0]).toMatchObject({...saved,locked:true});f.bag.compartments![1].opening.length=100;expect(f.plan().placements).toHaveLength(0);expect(f.trip.lockedPlacements).toEqual([saved]);expect(f.trip.completedInstanceIds).toEqual([saved.instanceId]);expect(samePlacementGeometry(saved,{...saved,compartmentId:'left'})).toBe(false);});
  it('explains removed assignments and preserves packed coordinates after reassignment',()=>{const f=fixture();f.trip.entries[0].containerId=f.bag.id;f.trip.entries[0].compartmentId='gone';expect(f.plan().excluded[0].reason).toContain('assigned compartment is missing');f.trip.entries[0].compartmentId='right';const saved=f.plan().placements[0];f.trip.lockedPlacements=[saved];f.trip.completedInstanceIds=[saved.instanceId];f.trip.entries[0].compartmentId='left';expect(f.plan().placements).toHaveLength(0);expect(f.trip.lockedPlacements).toEqual([saved]);expect(f.trip.completedInstanceIds).toEqual([saved.instanceId]);});
  it('isolates support contacts between compartments and requires their own reachable top',()=>{const f=fixture(),p=f.plan().placements[0],lower={...p,z:0,height:40},upper={...p,z:40,height:40,instanceId:'upper'};expect(geometryContactArea(upper,lower,new Map())).toBe(upper.length*upper.width);expect(geometryContactArea({...upper,compartmentId:'right'},lower,new Map())).toBe(0);expect(hasVerticalEntry(lower,[upper],new Map(),f.bag)).toBe(false);expect(fitsGeometrySpace({...p,x:170},f.bag,f.item)).toBe(false);expect(hasPackingAndTravelSupport({...p,z:1},[],new Map(),1,f.bag)).toBe(false);});
  it('retains compartment records and identities in backups and separate shared copies',()=>{const f=fixture();f.trip.entries[0].containerId=f.bag.id;f.trip.entries[0].compartmentId='right';f.trip.lockedPlacements=f.plan().placements;const backup={format:'packing-scanning-backup',app:f.app,photos:[]};expect(isPackingBackup(backup)).toBe(true);const records=sharedPackingRecords(f.app,f.trip.id),copy=openSharedPack(f.app,{id:'pack',householdId:'household',revision:1,name:'Pack',updatedAt:evidence.collectedAt,updatedBy:'member',records},'copy');const trip=copy.trips[0],p=buildPlan(trip,copy.libraryItems,copy.containers);expect(p.placements[0].compartmentId).toBe('right');expect(p.placements[0].containerId).toContain('shared-copy:');expect(copy.containers[0].compartments).toEqual(f.bag.compartments);f.bag.compartments![0].supportEvidence.source='estimated';expect(isPackingBackup(backup)).toBe(false);});
});
