import {beforeEach,describe,expect,it,vi} from 'vitest';
const fixture=vi.hoisted(()=>({native:true,platform:'android',available:true,bridge:{pickItemPhoto:vi.fn(),readItemPhoto:vi.fn(),discardItemPhoto:vi.fn()}}));
vi.mock('@capacitor/core',()=>({Capacitor:{isNativePlatform:()=>fixture.native,getPlatform:()=>fixture.platform,isPluginAvailable:()=>fixture.available},registerPlugin:()=>fixture.bridge}));
import {pickNativeItemPhoto,readNativeItemPhoto,nativeItemPhotosAvailable,discardNativeItemPhoto} from './native-item-photo';
import {isItemEditorDraft,type ItemEditorDraft} from './item-photo-draft';
const lease='11111111-1111-4111-8111-111111111111',ticket='22222222-2222-4222-8222-222222222222';
const draft:ItemEditorDraft={version:1,unit:'imperial',name:'',category:'medicine',length:'',width:'2.25',height:'',mass:'',dimensionSource:'estimated',massSource:'known',flexibility:'rigid',fragile:false,topLoad:'0',topLoadSource:'known',keepUpright:false,formsNeedRecovery:false,packingForms:[],scannedEstimate:false,scanDimensionsEdited:true,scaleReference:'',removePhoto:true};
const selected={ticket,target:'guest',selected:false,notice:'Cancelled; draft retained.'};
beforeEach(()=>{vi.resetAllMocks();fixture.native=true;fixture.platform='android';fixture.available=true;});
describe('native item photo drafts',()=>{
  it('allows incomplete fields without treating them as a saved item and refuses malformed or unknown versions',()=>{expect(isItemEditorDraft(draft)).toBe(true);expect(isItemEditorDraft({...draft,version:2})).toBe(false);expect(isItemEditorDraft({...draft,length:12})).toBe(false);expect(isItemEditorDraft({...draft,removePhoto:'false'})).toBe(false);});
  it('preserves a cancelled selection ticket and sends the captured lease and complete draft',async()=>{fixture.bridge.pickItemPhoto.mockResolvedValue(selected);expect(await pickNativeItemPhoto(draft,'camera',lease)).toEqual(selected);expect(fixture.bridge.pickItemPhoto).toHaveBeenCalledWith({lease,source:'camera',draftJson:JSON.stringify(draft)});});
  it('requires the Android plugin and a lease without using a browser file picker after failure',async()=>{fixture.available=false;expect(nativeItemPhotosAvailable()).toBe(false);await expect(pickNativeItemPhoto(draft,'library',lease)).rejects.toThrow(/Unlock/);fixture.available=true;await expect(pickNativeItemPhoto(draft,'library')).rejects.toThrow(/Unlock/);fixture.bridge.pickItemPhoto.mockRejectedValue(Error('storage refused'));await expect(pickNativeItemPhoto(draft,'library',lease)).rejects.toThrow('storage refused');});
  it('rejects malformed selection replies and photo paths or unsupported data URLs',async()=>{fixture.bridge.pickItemPhoto.mockResolvedValue({...selected,target:'outside'});await expect(pickNativeItemPhoto(draft,'library',lease)).rejects.toThrow(/not confirmed/);fixture.bridge.readItemPhoto.mockResolvedValue({draftJson:JSON.stringify(draft),dataUrl:'file:///private/photo.jpg'});await expect(readNativeItemPhoto(selected,lease)).rejects.toThrow(/invalid/);});
  it('reads a draft only through the new lease and exact ticket and keeps cancellation photo-free',async()=>{fixture.bridge.readItemPhoto.mockResolvedValue({draftJson:JSON.stringify(draft)});expect(await readNativeItemPhoto(selected,lease)).toEqual({draft,photo:undefined});expect(fixture.bridge.readItemPhoto).toHaveBeenCalledWith({lease,ticket});await discardNativeItemPhoto(selected);expect(fixture.bridge.discardItemPhoto).toHaveBeenCalledWith({ticket});});
});
