import {describe,it,expect} from 'vitest';
import {createInitialData} from './seed';
import {isPackingBackup,accountMetadataBackup} from './backup';
import {parseScanRetentionReply,recordRemovedScanSources,validScanRetentionDays} from './scan-retention';
import type {ScanRecord} from './types';
const id='11111111-1111-4111-8111-111111111111',at='2026-10-01T00:00:00Z';
const reply={version:1 as const,confirmedAt:at,removedIds:[id],checkedCount:1,deletedCount:1,skippedCount:0,failedCount:0,nextCursor:null};
const source:ScanRecord={id,target:'item',createdAt:'2026-09-01T00:00:00Z',platform:'android',method:'arcore_depth',completedPasses:6,modelStoredLocally:true};
describe('raw scan retention records',()=>{
  it('accepts only the supported periods while retaining legacy keep defaults',()=>{for(const days of [undefined,null,7,30,90])expect(validScanRetentionDays(days)).toBe(true);for(const days of [0,-1,1,8,NaN,Infinity,'7',{},true])expect(validScanRetentionDays(days)).toBe(false);});
  it('refuses malformed native confirmations before touching saved records',()=>{expect(parseScanRetentionReply(reply)).toEqual(reply);for(const patch of [{version:2},{confirmedAt:'bad'},{removedIds:[id,id]},{removedIds:['../source']},{deletedCount:2},{checkedCount:0},{skippedCount:101},{failedCount:-1},{nextCursor:undefined},{nextCursor:'path'}])expect(()=>parseScanRetentionReply({...reply,...patch})).toThrow('invalid confirmation');});
  it('changes only original availability while keeping dimensions, derivatives, photos and packed state exact',()=>{const data=structuredClone(createInitialData());data.libraryItems[0].scan=source;data.libraryItems[0].photoId='keep-photo';data.containers[0].scan={...source,target:'container_interior'};data.trips[0].completedInstanceIds=['entry-laptop#1'];const before=structuredClone(data),changed=recordRemovedScanSources(data,reply);expect(data).toEqual(before);expect(changed.trips).toBe(data.trips);expect(changed.libraryItems[0]).toEqual({...data.libraryItems[0],scan:{...source,modelStoredLocally:false,sourceRetention:{reason:'raw_scan_retention',confirmedAt:at}}});expect(changed.containers[0].inside).toBe(data.containers[0].inside);expect(changed.settings).toBe(data.settings);expect(recordRemovedScanSources(changed,{...reply,confirmedAt:'2026-10-02T00:00:00Z'})).toBe(changed);});
  it('does not apply another source ID or an Android cleanup to an iOS record',()=>{const data=structuredClone(createInitialData());data.libraryItems[0].scan={...source,platform:'ios',method:'guided_object_capture'};data.containers[0].scan={...source,id:'22222222-2222-4222-8222-222222222222',target:'container_interior'};expect(recordRemovedScanSources(data,reply)).toBe(data);});
  it('retains a valid policy in backup and account metadata without uploading original sources',()=>{const data=structuredClone(createInitialData());for(const days of [undefined,null,7,30,90] as const){data.settings.automaticScanDeletionDays=days;expect(isPackingBackup({format:'packing-scanning-backup',app:data,photos:[]})).toBe(true);}data.settings.automaticScanDeletionDays=7;data.libraryItems[0].scan=source;const account=accountMetadataBackup(data);expect(account.app.settings.automaticScanDeletionDays).toBe(7);expect(account.app.libraryItems[0].scan).toBeUndefined();const invalid=structuredClone(account);Object.assign(invalid.app.settings,{automaticScanDeletionDays:0});expect(isPackingBackup(invalid)).toBe(false);});
});
