import {afterEach,describe,expect,it,vi} from 'vitest';
const native=vi.hoisted(()=>({isNativePlatform:vi.fn(()=>false)}));
vi.mock('@capacitor/core',()=>({Capacitor:native}));
import {fetchWeather,weatherEndpoint} from './weather-client';
import {WEATHER_SOURCE} from './weather';
afterEach(()=>{vi.unstubAllGlobals();vi.unstubAllEnvs();native.isNativePlatform.mockReturnValue(false);});
describe('weather client privacy and protocol',()=>{
  it('uses same-origin web requests and requires an exact HTTPS origin in native builds',()=>{expect(weatherEndpoint()).toBe('/api/v1/weather');native.isNativePlatform.mockReturnValue(true);expect(weatherEndpoint()).toBeUndefined();for(const origin of ['http://example.test','https://user:secret@example.test','https://example.test/path','https://example.test/']){vi.stubEnv('VITE_WEATHER_API_ORIGIN',origin);expect(weatherEndpoint()).toBeUndefined();}vi.stubEnv('VITE_WEATHER_API_ORIGIN','https://example.test');expect(weatherEndpoint()).toBe('https://example.test/api/v1/weather');});
  it('sends only explicit lookup fields with no cookies, referrer or response caching',async()=>{const provider=vi.fn().mockResolvedValue(new Response(JSON.stringify({data:[]}),{headers:{'content-type':'application/json'}}));vi.stubGlobal('fetch',provider);const signal=new AbortController().signal;expect(await fetchWeather('/api/v1/weather','places',{q:'Berlin, Germany'},signal)).toEqual([]);expect(provider).toHaveBeenCalledWith('/api/v1/weather/places?q=Berlin%2C+Germany',{signal,credentials:'omit',cache:'no-store',referrerPolicy:'no-referrer'});});
  it('rejects oversized streamed data and changed content type before accepting a result',async()=>{for(const r of [new Response('x'.repeat(150001),{headers:{'content-type':'application/json'}}),new Response('{"data":[]}',{headers:{'content-type':'text/html'}})]){vi.stubGlobal('fetch',vi.fn().mockResolvedValue(r));await expect(fetchWeather('/api/v1/weather','places',{q:'Berlin'},new AbortController().signal)).rejects.toThrow();}});
  it('never accepts an invalid future forecast or silently converts provider failure into data',async()=>{const f={provider:'open_meteo',version:1,sourceUrl:WEATHER_SOURCE,sourceHash:'a'.repeat(64),retrievedAt:new Date(Date.now()+600000).toISOString(),place:{id:2950159,name:'Berlin',country:'Germany',countryCode:'DE',latitude:52.52,longitude:13.41,timezone:'Europe/Berlin'},gridLatitude:52.5,gridLongitude:13.4,days:[{date:'2026-10-01',minC:8,maxC:26,precipitationProbability:50}]};vi.stubGlobal('fetch',vi.fn().mockResolvedValue(new Response(JSON.stringify({data:f}),{headers:{'content-type':'application/json'}})));await expect(fetchWeather('/api/v1/weather','forecast',{placeId:'2950159'},new AbortController().signal)).rejects.toThrow(/Invalid/);vi.stubGlobal('fetch',vi.fn().mockResolvedValue(new Response('{}',{status:503})));await expect(fetchWeather('/api/v1/weather','forecast',{placeId:'2950159'},new AbortController().signal)).rejects.toThrow(/unchanged/);});
});
