import {describe,expect,it} from 'vitest';
import {createInitialData} from './seed';
import {isWeatherForecast,isSavedWeather,isWeatherPlace,reviewWeather,weatherSuggestions,WEATHER_SOURCE,type WeatherForecast} from './weather';
import {accountMetadataBackup,isPackingBackup} from './backup';
import {openSharedPack,sharedPackingRecords} from './shared-packs';
import {buildPlan} from './optimizer';

const at='2026-10-01T12:00:00Z',now=Date.parse(at);
export function forecastFixture():WeatherForecast{return {provider:'open_meteo',version:1,sourceUrl:WEATHER_SOURCE,sourceHash:'a'.repeat(64),retrievedAt:at,place:{id:2950159,name:'Berlin',country:'Germany',countryCode:'DE',latitude:52.52,longitude:13.41,timezone:'Europe/Berlin'},gridLatitude:52.5,gridLongitude:13.4,days:[{date:'2026-10-01',minC:8,maxC:26,precipitationProbability:50},{date:'2026-10-02',minC:null,maxC:20,precipitationProbability:null}]};}
function fixture(){const app=structuredClone(createInitialData()),trip=app.trips[0];trip.packingOnly=false;trip.destination='Berlin, Germany';trip.startDate='2026-10-01';trip.endDate='2026-10-03';trip.weather={destination:trip.destination,forecast:forecastFixture()};return {app,trip};}
describe('saved weather and bounded packing reminders',()=>{
  it('identifies actual covered dates and missing values without inventing a third day',()=>{const {trip}=fixture(),r=reviewWeather(trip,now);expect(r).toMatchObject({usable:true,covered:2,total:3,missingFields:2});expect(r.days).toHaveLength(2);});
  it('builds optional attributable reminders only for supported numeric values',()=>{const {trip}=fixture(),s=weatherSuggestions(trip,now);expect(s.map(v=>v.id)).toEqual(['weather-warm-layer','weather-light-clothing','weather-rain-layer']);expect(s.every(v=>v.priority==='optional'&&v.reason.includes('2 of 3')&&v.reason.includes('uncovered'))).toBe(true);});
  it('does not treat null precipitation as zero or null temperatures as actual conditions',()=>{const {trip}=fixture();trip.weather!.forecast.days=[{date:'2026-10-01',minC:null,maxC:null,precipitationProbability:null}];expect(weatherSuggestions(trip,now)).toEqual([]);expect(reviewWeather(trip,now).missingFields).toBe(3);});
  it('pauses reminders at the freshness boundary and never changes retrieval time',()=>{const {trip}=fixture(),before=structuredClone(trip);expect(weatherSuggestions(trip,now+6*3600000)).toEqual([]);expect(reviewWeather(trip,now+6*3600000).reason).toContain('stale');expect(trip).toEqual(before);});
  it('refuses future clock values rather than treating them as indefinitely fresh',()=>{const {trip}=fixture();expect(reviewWeather(trip,now-600000).reason).toContain('future');expect(weatherSuggestions(trip,now-600000)).toEqual([]);});
  it('binds saved advice to the reviewed destination while tolerating case and whitespace',()=>{const {trip}=fixture();trip.destination=' berlin,   GERMANY ';expect(reviewWeather(trip,now).usable).toBe(true);trip.destination='Tokyo';expect(reviewWeather(trip,now).reason).toContain('destination changed');expect(weatherSuggestions(trip,now)).toEqual([]);});
  it('preserves sources but pauses packing-only weather advice',()=>{const {trip}=fixture();trip.packingOnly=true;expect(reviewWeather(trip,now).reason).toContain('packing-only');expect(weatherSuggestions(trip,now)).toEqual([]);expect(trip.weather).toBeDefined();});
  it('explains invalid, reversed and uncovered dates',()=>{const {trip}=fixture();for(const [start,end] of [['2026-02-30','2026-10-02'],['2026-10-03','2026-10-01'],['2027-01-01','2027-01-02']]){trip.startDate=start;trip.endDate=end;expect(reviewWeather(trip,now).usable).toBe(false);expect(weatherSuggestions(trip,now)).toEqual([]);}});
  it('does not replace trip context or existing item geometry when dates change',()=>{const {app,trip}=fixture(),before=structuredClone(app),plan=buildPlan(trip,app.libraryItems,app.containers);trip.endDate='2026-10-02';expect(reviewWeather(trip,now)).toMatchObject({covered:2,total:2});expect(buildPlan(trip,app.libraryItems,app.containers).placements).toEqual(plan.placements);expect(app.libraryItems).toEqual(before.libraryItems);});
  it('rejects missing, duplicate and invalid weather records',()=>{const forecast=forecastFixture();for(const change of [()=>({...forecast,days:[]}),()=>({...forecast,sourceUrl:'https://other.test'}),()=>({...forecast,sourceHash:'fake'}),()=>({...forecast,days:[...forecast.days,forecast.days[0]]}),()=>({...forecast,days:[{...forecast.days[0],minC:NaN}]}),()=>({...forecast,days:[{...forecast.days[0],minC:30,maxC:20}]}),()=>({...forecast,days:[{...forecast.days[0],precipitationProbability:101}]}),()=>({...forecast,secret:'token'})])expect(isWeatherForecast(change())).toBe(false);expect(isWeatherPlace({...forecast.place,timezone:'Not/A_Zone'})).toBe(false);expect(isSavedWeather({destination:'',forecast})).toBe(false);});
  it('retains exact forecast values, original timestamps and saved context in ordinary/private backups',()=>{const {app,trip}=fixture();const backup=JSON.parse(JSON.stringify({format:'packing-scanning-backup',app,photos:[]}));expect(isPackingBackup(backup)).toBe(true);expect(backup.app.trips[0].weather).toEqual(trip.weather);expect(accountMetadataBackup(app).app.trips[0].weather).toEqual(trip.weather);backup.app.trips[0].weather.forecast.days[0].date='2026-02-30';expect(isPackingBackup(backup)).toBe(false);});
  it('keeps forecast identities independent from household record remapping',()=>{const {app,trip}=fixture(),records=sharedPackingRecords(app,trip.id),copy=openSharedPack(app,{id:'server-pack',householdId:'household',name:trip.name,revision:1,updatedAt:trip.updatedAt,updatedBy:'owner',records},'weather-copy');expect(copy.trips[0].weather).toEqual(trip.weather);expect(sharedPackingRecords(copy,copy.activeTripId).trip.weather).toEqual(trip.weather);});
  it('supports legacy packs with no forecast without inferring destination weather',()=>{const {trip}=fixture();delete trip.weather;expect(weatherSuggestions(trip,now)).toEqual([]);expect(reviewWeather(trip,now).usable).toBe(false);});
});
